preserve_hierarchy: 1
files:
  - source: upload/admin/language/pt-br/**/*.php
    translation: admin/**/%file_name%.%file_extension%
  - source: upload/catalog/language/pt-br/**/*.php
    translation: catalog/**/%file_name%.%file_extension%
  - source: upload/install/language/pt-br/**/*.php
    translation: install/**/%file_name%.%file_extension%
  - source: upload/extension/opencart/admin/language/pt-br/**/*.php
    translation: extension/opencart/admin/**/%file_name%.%file_extension%
  - source: upload/extension/opencart/catalog/language/pt-br/**/*.php
    translation: extension/opencart/catalog/**/%file_name%.%file_extension%
